### ISSUE TITLE
How to know if it worked?

### ISSUE THREAD

**Issue by gregveres** [CZEMacLeod/C3D.MSBuild.Tools.EF6.GenerateViews#3]
I am using code first migrations. In VS2019, I used EF Power Tools to give me an Entity Framework menu on my DBContext class file in the solution explorer.
When I selected Generate Views, it would take about a minute to generate the views. The result was a DBContext.Views.cs file added to the project. 

Since EF Power Tools isn't available for VS2022, I am trying to migrate to your build tool. It sounds great but I am not sure I have it installed properly. 

Here is what I did:
1. I installed the NuGet package into my MVC Project. I have many projects within the solution. The SkyCourt project is the start up project that is where the MVC app lives. This is also where the migrations live. I have another project called SkyCourt.Models that is where the DBContext class lives. This is where the .Views.cs file used to live.
2. I deleted the .Views.cs file from my project
3. I unloaded the SkyCourt project and edited the file to add the code snippet from the main page of your project.
4. I loaded the project and made a change to the model.
5. I then opened the package manager and ran Add-Migration
6. I then ran Update-Database

Everything went well, but I am not sure that that the Views were created. I have no .edmx in my solution view. And when I did the Udpate-Database, it took about 2 seconds where normally view generation takes about 60 seconds. 

I looked in the obj directory for SkyCourt and I do not see anything called EntityViews. 

Did I miss something? 

Thanks

**Comment by gregveres** [comment]
I searched my project for .edmx files and there are none. Should there be when using code first migrations?
In the migration folder there are .cs and .resx files but no .edmx files.

**Comment by CZEMacLeod** [comment]
Okay. I suggest you add another project to your solution that is just the console app - similar to the sample, but adjusted to look at your Models project and DbContext. I am slightly surprised your migrations are not in the same project as the DbContext, but that is your choice.
When you run the console app, it should generate an edmx file next to the assembly dll (with the same name as the assembly but with an .edmx extension). This will probably be in the bin/Debug folder.
Copy that file to your models project, which should also have the nuget package, and set the build type to EntityView, and set the Custom Tool Namespace to the same as your DbContext.

In the future, when you run Add-Migration, you will need to re-run the console app and copy the new EDMX file to your Models project.

I don't actually use Add-Migration /  Update-Database myself - I have some code that detects if a migration is needed, and generates the code and edmx into the migrations folder. This occurs when I first run the project after making model changes. I then recompile, including the new migration, which also updates the views, and when it starts up the second time, it applies the new migration code. This way I avoid all the issues with startup projects, and the powershell stuff not working correctly in VS2022. But that is just my workflow.

**Comment by gregveres** [comment]
Thanks for the info. 

Are you saying:
1. The process is not automatic if I am using code-first migrations?
2. The process would be automatic if my DbContext and migrations were in the same project?

I could move the migrations into the Models project. They were in the main project by default when the application started before I started pulling parts into different projects. We just never thought about moving the migrations into the Models project. They seem to be more a part of the app rather than part of the model. But I could go either way.

**Comment by CZEMacLeod** [comment]
@gregveres 1) The process is not fully automatic. When using the extension, it wasn't either - you had to manually trigger the generate views command.
2) It could be more automatic if the migrations were in the DbContext project. I always assume that the models can go in a separate project, but that the context and migrations should be in the same project. I then have the app in a third project. Obviously, the models can be in the same project as the context if you don't want to fully break it up.

You can make it nearly fully automatic by creating the command line project to handle the model changes/migration creation and outputting the latest edmx file.

Technically the edmx associated with each migration is actually stored in the resx file as "Target" - it is a Base64 encoded GZip of the source. I guess it would be possible to add the step to pull the edmx from the migrations to the build task. I might have a look at adding that, or I would accept a PR ;)
